[build]
  command = "npm run build"
  publish = "./dist"

[dev]
  command = ""
  publish = "./dist"

[functions]
  node_bundler = "esbuild"


[[redirects]]
  from = "/qr/*"
  to = "/.netlify/functions/show-qr"
  status = 200


# Do this instead of looking for a shortlink redirect 
[[redirects]]
  from = "/image/*"
  to = "/image/:splat"
  status = 200


# Catch-all for any unfound short codes
[[redirects]]
  from = "*"
  to = "https://www.hawksworx.com/blog/find-that-at/"
  status = 302

